### ISSUE TITLE
Examples / Documentation

### ISSUE THREAD

**Issue by xeoneox** [Talinx/velero-plugin-for-webdav#1]
I'm having trouble getting this plugin working through ArgoCD. It would be nice to have some basic docs or examples to follow

**Comment by Talinx** [comment]
Docs and an update to the latest velero version would certainly be useful, I will have time for this in early April.

I am not very familiar with ArgoCD, I hope I can help somewhat anyway. If you use helm, you can use this plugin with [this helm chart](https://vmware-tanzu.github.io/helm-charts) by setting these options (customize them for your URL, username etc.):

```yaml
image:
  repository: "talinx/velero"
  tag: "v1.13.0"

configuration:
  uploaderType: "kopia"
  backupStorageLocation:
  - provider: "talinx.dev/webdav-object-store-plugin"
    bucket: "..."
    config:
    - root: "https://..."
      user: "mywebdavusername"
      webDAVPassword: "mysecretpassword"
      webDAVUrl: "https://..."
      username: "mywebdavusername"
      password: "mysecretpassword"
      bucketsDir: "..."
  volumeSnapshotLocation:
  - name: "not-used"
  defaultVolumesToFsBackup: true

initContainers:
  name: "velero-plugin-for-webdav"
  image: "talinx/velero-plugin-for-webdav:1.0"
  volumeMounts:
  - mountPath: "/target"
    name: "plugins"

snapshotsEnabled: false
deployNodeAgent: true

nodeAgent:
  privileged: true
```

I will happily explain any option that is not immediately clear.

What did you try so far with ArgoCD?
